services:
  # A Docker web service
  - type: web
    name: vaultwarden-render
    runtime: docker
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        property: connectionString
        sync: false
      - key: ADMIN_TOKEN
        type: password
        generateValue: true
        
