services:
- type: pserv
  name: mysql
  plan: standard
  env: docker
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: VaultWarden
  envVars:
  - key: ADMIN_TOKEN
    generatevalue: true
  - key: DATABASE_MAX_CONNS
    value: 7
  - key: DOMAIN
    value: https://vaultwarden-darkredtitan.herokuapp.com
  - key: SIGNUPS_ALLOWED
    value: false
  - key: WEB_VAULT_ENABLED
    value: false
