services:
  # A Docker web service
  - type: web
    plan: free
    name: vaultwarden-render
    runtime: image
    image:
      url: vaultwarden/server:latest
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        property: connectionString
        sync: false
      - key: ADMIN_TOKEN
        type: password
        generateValue: true
      
